@base_url = {{$dotenv REST_CLIENT_URL}}/api
@url={{base_url}}/author

GET {{url}}

###

GET {{url}}?page=1&count=5

###

GET {{url}}/id/1

###

GET {{url}}/detailed

###

GET {{url}}/detailed?page=1&count=5

###

GET {{url}}/id/1/detailed

###

POST {{url}}
Content-Type: application/json

{
    "bookId": 1,
    "name": "Name 1"
}

###

PUT {{url}}/id/1
Content-Type: application/json

{
    "bookId": 1,
    "name": "Name 1"
}

###

DELETE {{url}}/id/1

###